# _config.yml
author: PolicyEngine
title: PolicyEngine
copyright: "2025"
logo: logo.png

execute:
  execute_notebooks: cache
  stderr_output: error
  timeout: 600

repository:
  url: https://github.com/policyengine/policyengine.py
  branch: master
  path_to_book: docs

title: Python documentation

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.js
    html_theme: furo
    pygments_style: default
    html_css_files:
      - style.css
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinxcontrib.autodoc_pydantic"

only_build_toc_files: true